### PR TITLE
Adding service for bond-watch

### PR DESCRIPTION
**Pull request by irathore**
Please check and merge. I still need a system without containers to test it.

### CODE REVIEW

**Comment by kentwu1** [comment]
Can we test it out before we go ahead to merge it then?

**Comment by irathore** [comment]
I tested  build from my branch and it worked like a charm

[root@overcloud-compute-0 ~]# yum install ~heat-admin/apicapi-1.6.1-202.el7.noarch.rpm
[root@overcloud-compute-0 ~]# systemctl start bondwatch
[root@overcloud-compute-0 ~]# ps ax|grep bond
 742767 ?        Ss     0:00 /usr/bin/python2 /usr/bin/apic-bond-watch
 742822 pts/0    S+     0:00 grep --color=auto bond
[root@overcloud-compute-0 ~]# systemctl stop bondwatch
[root@overcloud-compute-0 ~]# ps ax|grep bond
 743484 pts/0    S+     0:00 grep --color=auto bond
[root@overcloud-compute-0 ~]#

**Comment by tbachman** [comment]
Can we create a similar pull-request for debian?

**Comment by tbachman** [comment]
And thanks for the fix! :-)

**Comment by irathore** [comment]
Yes I will create it.

**Pull request merged**
